# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbc8a8e8afde06ca6cc4d20b5129270f81fb9ccbc03c16da3c831b3b6a9b23c2db08e1cdfa60b6d3938cf3c828f91e4a29bfbece3464e0e367d566d80be3fc6e

test:
  secret_key_base: d2e2276ec6f6b4d3a5de9c825c618beb07f287ef70ab2e13fffca89c5f3e3ab0500fcc38e3d84a70332a609a086cde3a3ff211514eabfcf169652afc216ddf15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
